sudo: required

language: c

addons:
  apt:
    packages:
      - strace
      - graphviz
      - libfuse-dev

before_install:
  # Build tup - No package is provided on the travis machines
  - git clone git://github.com/gittup/tup.git $HOME/tup
  - (cd $HOME/tup; ./bootstrap.sh)

script:
  - (cd $HOME/trash; pwd; ls; PATH=$PATH:$HOME/tup tup upd)
