sudo: required

language: c

addons:
  apt:
    packages:
      - strace
      - graphviz
      - libfuse-dev

before_install:
  - git clone git://github.com/gittup/tup.git $HOME/tup
  - $HOME/tup/bootstrap.sh

script: scripts/travis_build.sh
